#!/bin/sh
set -eu

cd "$(dirname $0)"

config_file=uwsgi.ini

[ -f config.py ] || (
  echo "no config.py found!"
  exit 1
)

(set -eu
  sleep 10
  
  # check whether backend is available
  curl -s "http://localhost:5002" >/dev/null
  
  while true; do
    ./manage.py runcrons
    sleep 60
  done
) &

exec poetry run uwsgi $config_file "$@"
