# Generated by Django 2.2.10 on 2020-03-29 16:17

from django.db import migrations, models
import schema.fee_util


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0003_auto_20200329_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeentry",
            name="detect_method",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("FEE_COMMAND", "Fee_command"),
                    ("LAST_FEE", "Last_fee"),
                    ("MULTIPLE_OF_FEE", "Multiple_of_fee"),
                    ("MULTIPLE_OF_COMMON_FEE", "Multiple_of_common_fee"),
                    ("FALLBACK", "Fallback"),
                ],
                default=schema.fee_util.DetectMethod(0),
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="feeentry",
            name="pay_interval",
            field=models.CharField(max_length=32),
        ),
    ]
