# Generated by Django 2.2.10 on 2020-03-29 16:18

from django.db import migrations, models
import schema.fee_util


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0004_auto_20200329_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeentry",
            name="detect_method",
            field=models.TextField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("FEE_COMMAND", "Fee_command"),
                    ("LAST_FEE", "Last_fee"),
                    ("MULTIPLE_OF_FEE", "Multiple_of_fee"),
                    ("MULTIPLE_OF_COMMON_FEE", "Multiple_of_common_fee"),
                    ("FALLBACK", "Fallback"),
                ],
                default=schema.fee_util.DetectMethod(0),
            ),
        ),
        migrations.AlterField(
            model_name="feeentry",
            name="pay_interval",
            field=models.TextField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("SIX_MONTH", "Six_month"),
                    ("YEARLY", "Yearly"),
                    ("VARIABLE", "Variable"),
                ]
            ),
        ),
    ]
