# Generated by Django 2.2.10 on 2020-03-29 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0005_auto_20200329_1618"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="id", new_name="bank_type_id"
        ),
    ]
