# Generated by Django 3.2.24 on 2024-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0007_fix_detect_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="original_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
