# Generated by Django 2.2.10 on 2020-03-29 16:07

from django.db import migrations, models
import schema.fee_util


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_feeentry_detect_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeentry',
            name='detect_method',
            field=models.TextField(choices=[('MANUAL', 'Manual'), ('FEE_COMMAND', 'Fee_command'), ('LAST_FEE', 'Last_fee'), ('MULTIPLE_OF_FEE', 'Multiple_of_fee'), ('MULTIPLE_OF_COMMON_FEE', 'Multiple_of_common_fee'), ('FALLBACK', 'Fallback')], default=schema.fee_util.DetectMethod(0)),
        ),
    ]
