# Generated by Django 2.2.10 on 2020-03-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_rename_tx_id'),
    ]

    operations = [
        migrations.RunSQL("""update fee_entry set detect_method = 'FALLBACK' where detect_method='DetectMethod.FALLBACK';
        """)
    ]
