#!/bin/sh
set -eu

cd "$(dirname $0)/.."

pwd

config_file=configs/uwsgi.ini

(set -eu
  sleep 10

  # check whether backend is available
  curl -s "http://localhost:5002" >/dev/null

  while true; do
    uv run scripts/manage.py runcrons
    sleep 60
  done
) &

exec uv run uwsgi $config_file "$@"

